### ISSUE TITLE
fix ur code

### ISSUE THREAD

**Issue by cattyngmd** [RealzPrestige/Mint-Public#1]
nigga u literally pasted phobos hahaahaha

https://github.com/RealzPrestige/Mint-Public/blob/2cd23c9ea432da5fe07e9e28d0d8dfe52ee99683/src/main/java/mint/modules/visual/HoleESP.java#L95
hahahhhaha

**Comment by RealzPrestige** [comment]
who r u?

**Comment by cattyngmd** [comment]
> who r u?

phobos paster shut up
